services:
  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./web:/var/www/html
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mariadb_data: