services:
  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    env_file:
      - .env
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./web:/var/www/html
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  mariadb_data: